version: "3.9"
services:
  dbpost:
    image: postgres:latest
    environment:
      POSTGRES_DB: Work9
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 486820
    volumes:
      - ./data3:/var/lib/postgresql/data
      - ./init_scripts/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - 5435:5432
